---
- hosts: all
  tasks:
  - name: Create rocknsm dir
    file:
      path: /opt/rocknsm/
      state: directory
      mode: 0755
      owner: root
      group: root
  - name: Create dist file if it doesn't exist
    copy:
      src: files/rocknsm_config.yml.dist
      dest: /opt/rocknsm/config.yml.dist
      owner: root
      group: root
      mode: 0644
  - name: Read in variables
    include_vars: /opt/rocknsm/config.yml.dist
  - name: Create config directory
    file:
      state: directory
      owner: root
      group: root
      mode:  0755
      path: /etc/rocknsm
  - name: Render template
    template:
      backup: yes
      src: templates/rock_config.yml.j2
      dest: /etc/rocknsm/config.yml
      owner: root
      group: root
      mode: 0644
